#!/bin/bash

res=$(echo "restart;shutdown" | rofi -sep ";" -dmenu -p "" -width 250)

if [ $res = "restart" ]; then
    systemctl reboot
fi
if [ $res = "shutdown" ]; then
    systemctl poweroff
fi
exit 0